name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88
        with:
          toolchain: 1.85.1
      - run: cargo fmt --check
      - run: cargo check --locked
      - run: cargo clippy --locked -- -D warnings
      - run: cargo test --locked
      - run: cargo build --locked
